// <auto-generated />
namespace Broadway.WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class relationAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(relationAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202106021203032_relationAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
